development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: sumu 
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: sumu
  password: 
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: sumu
  password: 